nota1 = float(input('qual sua nota 1:'))
nota2 = float(input('qual sua nota 2:'))
nota3 = float(input('qual sua nota 3:'))
nota4 = float(input('qual sua nota 4:'))
print("sua média é",(nota1+nota2+nota3+nota4)/4)